package com.mj.config;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

import com.mj.model.base.AttachFile;
import com.mj.model.base.Product;
import com.mj.model.biz.ProdDeaily;
import com.mj.model.biz.ProdStock;
import com.mj.model.biz.ProdStockLog;
import com.mj.model.mst.ProdCategory;
import com.mj.model.system.BatchJob;
import com.mj.model.system.BatchJobLogger;
import com.mj.model.system.Dict;
import com.mj.model.system.DictEnum;
import com.mj.model.system.ExcelImportLog;
import com.mj.model.system.ExceptionLog;
import com.mj.model.system.GlobalConfig;
import com.mj.model.system.Log;
import com.mj.model.system.Menu;
import com.mj.model.system.Role;
import com.mj.model.system.RoleResource;
import com.mj.model.system.User;
import com.mj.model.system.UserRole;
/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("base_attach_file", "id", AttachFile.class);
		arp.addMapping("base_product", "id", Product.class);
		arp.addMapping("biz_prod_deaily", "id", ProdDeaily.class);
		arp.addMapping("biz_prod_stock", "id", ProdStock.class);
		arp.addMapping("biz_prod_stock_log", "id", ProdStockLog.class);
		arp.addMapping("mst_prod_category", "id", ProdCategory.class);
		arp.addMapping("sys_batch_job", "id", BatchJob.class);
		arp.addMapping("sys_batch_job_logger", "id", BatchJobLogger.class);
		arp.addMapping("sys_dict", "id", Dict.class);
		arp.addMapping("sys_dict_enum", "id", DictEnum.class);
		arp.addMapping("sys_excel_import_log", "id", ExcelImportLog.class);
		arp.addMapping("sys_exception_log", "id", ExceptionLog.class);
		arp.addMapping("sys_global_config", "id", GlobalConfig.class);
		arp.addMapping("sys_log", "id", Log.class);
		arp.addMapping("sys_menu", "id", Menu.class);
		arp.addMapping("sys_role", "id", Role.class);
		arp.addMapping("sys_role_resource", "id", RoleResource.class);
		arp.addMapping("sys_user", "id", User.class);
		arp.addMapping("sys_user_role", "id", UserRole.class);
	}
}


