package com.mj.model.mst;

import com.mj.bean.mst.BaseProdCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProdCategory extends BaseProdCategory<ProdCategory> {
	public static final ProdCategory dao = new ProdCategory();
}
