package com.mj.bean.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAttachFile<M extends BaseAttachFile<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}

	public java.lang.String getUserId() {
		return get("user_id");
	}

	public void setFolderId(java.lang.Integer folderId) {
		set("folder_id", folderId);
	}

	public java.lang.Integer getFolderId() {
		return get("folder_id");
	}

	public void setFileName(java.lang.String fileName) {
		set("file_name", fileName);
	}

	public java.lang.String getFileName() {
		return get("file_name");
	}

	public void setFileSuffix(java.lang.String fileSuffix) {
		set("file_suffix", fileSuffix);
	}

	public java.lang.String getFileSuffix() {
		return get("file_suffix");
	}

	public void setFileSize(java.lang.Integer fileSize) {
		set("file_size", fileSize);
	}

	public java.lang.Integer getFileSize() {
		return get("file_size");
	}

	public void setThumbFlg(java.lang.String thumbFlg) {
		set("thumb_flg", thumbFlg);
	}

	public java.lang.String getThumbFlg() {
		return get("thumb_flg");
	}

	public void setStoreUrl(java.lang.String storeUrl) {
		set("store_url", storeUrl);
	}

	public java.lang.String getStoreUrl() {
		return get("store_url");
	}

	public void setThumbUrl(java.lang.String thumbUrl) {
		set("thumb_url", thumbUrl);
	}

	public java.lang.String getThumbUrl() {
		return get("thumb_url");
	}

	public void setQcloudUrl(java.lang.String qcloudUrl) {
		set("qcloud_url", qcloudUrl);
	}

	public java.lang.String getQcloudUrl() {
		return get("qcloud_url");
	}

	public void setQcloudThumbUrl(java.lang.String qcloudThumbUrl) {
		set("qcloud_thumb_url", qcloudThumbUrl);
	}

	public java.lang.String getQcloudThumbUrl() {
		return get("qcloud_thumb_url");
	}

	public void setTags(java.lang.String tags) {
		set("tags", tags);
	}

	public java.lang.String getTags() {
		return get("tags");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setAttachType(java.lang.Integer attachType) {
		set("attach_type", attachType);
	}

	public java.lang.Integer getAttachType() {
		return get("attach_type");
	}

	public void setFileMd5(java.lang.String fileMd5) {
		set("file_md5", fileMd5);
	}

	public java.lang.String getFileMd5() {
		return get("file_md5");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setAttachtType(java.lang.String attachtType) {
		set("attacht_type", attachtType);
	}

	public java.lang.String getAttachtType() {
		return get("attacht_type");
	}

	public void setTargetedProductCategory(java.lang.String targetedProductCategory) {
		set("targeted_product_category", targetedProductCategory);
	}

	public java.lang.String getTargetedProductCategory() {
		return get("targeted_product_category");
	}

}
