package com.mj.bean.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProduct<M extends BaseProduct<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setProductNo(java.lang.String productNo) {
		set("product_no", productNo);
	}

	public java.lang.String getProductNo() {
		return get("product_no");
	}

	public void setProductName(java.lang.String productName) {
		set("product_name", productName);
	}

	public java.lang.String getProductName() {
		return get("product_name");
	}

	public void setCategoryL1Id(java.lang.Integer categoryL1Id) {
		set("category_l1_id", categoryL1Id);
	}

	public java.lang.Integer getCategoryL1Id() {
		return get("category_l1_id");
	}

	public void setCategoryL2Id(java.lang.Integer categoryL2Id) {
		set("category_l2_id", categoryL2Id);
	}

	public java.lang.Integer getCategoryL2Id() {
		return get("category_l2_id");
	}

	public void setProductDesc(java.lang.String productDesc) {
		set("product_desc", productDesc);
	}

	public java.lang.String getProductDesc() {
		return get("product_desc");
	}

	public void setProductImages(java.lang.String productImages) {
		set("product_images", productImages);
	}

	public java.lang.String getProductImages() {
		return get("product_images");
	}

	public void setProductCover(java.lang.String productCover) {
		set("product_cover", productCover);
	}

	public java.lang.String getProductCover() {
		return get("product_cover");
	}

	public void setColor(java.lang.String color) {
		set("color", color);
	}

	public java.lang.String getColor() {
		return get("color");
	}

	public void setSpecs(java.lang.String specs) {
		set("specs", specs);
	}

	public java.lang.String getSpecs() {
		return get("specs");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setOutPrice(java.math.BigDecimal outPrice) {
		set("out_price", outPrice);
	}

	public java.math.BigDecimal getOutPrice() {
		return get("out_price");
	}

	public void setTotalProfit(java.math.BigDecimal totalProfit) {
		set("total_profit", totalProfit);
	}

	public java.math.BigDecimal getTotalProfit() {
		return get("total_profit");
	}

	public void setPriceUnit(java.lang.String priceUnit) {
		set("price_unit", priceUnit);
	}

	public java.lang.String getPriceUnit() {
		return get("price_unit");
	}

	public void setStockUnit(java.lang.String stockUnit) {
		set("stock_unit", stockUnit);
	}

	public java.lang.String getStockUnit() {
		return get("stock_unit");
	}

	public void setOrderNum(java.lang.Integer orderNum) {
		set("order_num", orderNum);
	}

	public java.lang.Integer getOrderNum() {
		return get("order_num");
	}

	public void setValidFlg(java.lang.String validFlg) {
		set("valid_flg", validFlg);
	}

	public java.lang.String getValidFlg() {
		return get("valid_flg");
	}

	public void setCreator(java.lang.String creator) {
		set("creator", creator);
	}

	public java.lang.String getCreator() {
		return get("creator");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setUpdator(java.lang.String updator) {
		set("updator", updator);
	}

	public java.lang.String getUpdator() {
		return get("updator");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}

	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

}
