package com.mj.model.biz;

import com.mj.bean.biz.BaseProdStockLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProdStockLog extends BaseProdStockLog<ProdStockLog> {
	public static final ProdStockLog dao = new ProdStockLog();
}
