package com.mj.model.biz;

import com.mj.bean.biz.BaseProdDeaily;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProdDeaily extends BaseProdDeaily<ProdDeaily> {
	public static final ProdDeaily dao = new ProdDeaily();
}
