package com.mj.model.biz;

import com.mj.bean.biz.BaseProdStock;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProdStock extends BaseProdStock<ProdStock> {
	public static final ProdStock dao = new ProdStock();
}
