package com.mj.model.system;

import com.mj.bean.system.BaseBatchJob;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BatchJob extends BaseBatchJob<BatchJob> {
	public static final BatchJob dao = new BatchJob();
}
