package com.mj.model.system;

import com.mj.bean.system.BaseBatchJobLogger;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BatchJobLogger extends BaseBatchJobLogger<BatchJobLogger> {
	public static final BatchJobLogger dao = new BatchJobLogger();
}
