package com.mj.model.system;

import com.mj.bean.system.BaseDictEnum;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DictEnum extends BaseDictEnum<DictEnum> {
	public static final DictEnum dao = new DictEnum();
}
