package com.mj.model.system;

import com.mj.bean.system.BaseDict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dict extends BaseDict<Dict> {
	public static final Dict dao = new Dict();
}
