package com.mj.model.system;

import com.mj.bean.system.BaseExcelImportLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExcelImportLog extends BaseExcelImportLog<ExcelImportLog> {
	public static final ExcelImportLog dao = new ExcelImportLog();
}
