package com.mj.model.system;

import com.mj.bean.system.BaseExceptionLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExceptionLog extends BaseExceptionLog<ExceptionLog> {
	public static final ExceptionLog dao = new ExceptionLog();
}
