package com.mj.model.system;

import com.mj.bean.system.BaseGlobalConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GlobalConfig extends BaseGlobalConfig<GlobalConfig> {
	public static final GlobalConfig dao = new GlobalConfig();
}
