package com.mj.model.system;

import com.mj.bean.system.BaseRoleResource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleResource extends BaseRoleResource<RoleResource> {
	public static final RoleResource dao = new RoleResource();
}
