package com.mj.bean.biz;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProdDeaily<M extends BaseProdDeaily<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setProdId(java.lang.String prodId) {
		set("prod_id", prodId);
	}

	public java.lang.String getProdId() {
		return get("prod_id");
	}

	public void setStock(java.lang.Integer stock) {
		set("stock", stock);
	}

	public java.lang.Integer getStock() {
		return get("stock");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setOutPrice(java.math.BigDecimal outPrice) {
		set("out_price", outPrice);
	}

	public java.math.BigDecimal getOutPrice() {
		return get("out_price");
	}

	public void setProfit(java.math.BigDecimal profit) {
		set("profit", profit);
	}

	public java.math.BigDecimal getProfit() {
		return get("profit");
	}

	public void setDeaily(java.util.Date deaily) {
		set("deaily", deaily);
	}

	public java.util.Date getDeaily() {
		return get("deaily");
	}

	public void setCreator(java.lang.String creator) {
		set("creator", creator);
	}

	public java.lang.String getCreator() {
		return get("creator");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setUpdator(java.lang.String updator) {
		set("updator", updator);
	}

	public java.lang.String getUpdator() {
		return get("updator");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}

	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

}
