package com.mj.bean.biz;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProdStock<M extends BaseProdStock<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setProdId(java.lang.String prodId) {
		set("prod_id", prodId);
	}

	public java.lang.String getProdId() {
		return get("prod_id");
	}

	public void setStockNum(java.lang.Integer stockNum) {
		set("stock_num", stockNum);
	}

	public java.lang.Integer getStockNum() {
		return get("stock_num");
	}

	public void setBookNum(java.lang.Integer bookNum) {
		set("book_num", bookNum);
	}

	public java.lang.Integer getBookNum() {
		return get("book_num");
	}

	public void setSkuNo(java.lang.String skuNo) {
		set("sku_no", skuNo);
	}

	public java.lang.String getSkuNo() {
		return get("sku_no");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setCreator(java.lang.String creator) {
		set("creator", creator);
	}

	public java.lang.String getCreator() {
		return get("creator");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}

	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public void setUpdator(java.lang.String updator) {
		set("updator", updator);
	}

	public java.lang.String getUpdator() {
		return get("updator");
	}

}
