package com.mj.bean.biz;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProdStockLog<M extends BaseProdStockLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setProdId(java.lang.String prodId) {
		set("prod_id", prodId);
	}

	public java.lang.String getProdId() {
		return get("prod_id");
	}

	public void setProdStockId(java.lang.String prodStockId) {
		set("prod_stock_id", prodStockId);
	}

	public java.lang.String getProdStockId() {
		return get("prod_stock_id");
	}

	public void setLogType(java.lang.Integer logType) {
		set("log_type", logType);
	}

	public java.lang.Integer getLogType() {
		return get("log_type");
	}

	public void setQuantity(java.lang.Integer quantity) {
		set("quantity", quantity);
	}

	public java.lang.Integer getQuantity() {
		return get("quantity");
	}

	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}

	public java.math.BigDecimal getPrice() {
		return get("price");
	}

	public void setStockAttachs(java.lang.String stockAttachs) {
		set("stock_attachs", stockAttachs);
	}

	public java.lang.String getStockAttachs() {
		return get("stock_attachs");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setImportAttachId(java.lang.String importAttachId) {
		set("import_attach_id", importAttachId);
	}

	public java.lang.String getImportAttachId() {
		return get("import_attach_id");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}

	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public void setUpdator(java.lang.String updator) {
		set("updator", updator);
	}

	public java.lang.String getUpdator() {
		return get("updator");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setCreator(java.lang.String creator) {
		set("creator", creator);
	}

	public java.lang.String getCreator() {
		return get("creator");
	}

}
