package com.mj.bean.system;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLog<M extends BaseLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}

	public java.lang.String getUserId() {
		return get("user_id");
	}

	public void setLogTime(java.util.Date logTime) {
		set("log_time", logTime);
	}

	public java.util.Date getLogTime() {
		return get("log_time");
	}

	public void setLogType(java.lang.Integer logType) {
		set("log_type", logType);
	}

	public java.lang.Integer getLogType() {
		return get("log_type");
	}

	public void setExecutive(java.lang.String executive) {
		set("executive", executive);
	}

	public java.lang.String getExecutive() {
		return get("executive");
	}

	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}

	public java.lang.String getIp() {
		return get("ip");
	}

	public void setAction(java.lang.String action) {
		set("action", action);
	}

	public java.lang.String getAction() {
		return get("action");
	}

}
