package com.mj.bean.system;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBatchJobLogger<M extends BaseBatchJobLogger<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setJobId(java.lang.Integer jobId) {
		set("job_id", jobId);
	}

	public java.lang.Integer getJobId() {
		return get("job_id");
	}

	public void setJobRunTime(java.util.Date jobRunTime) {
		set("job_run_time", jobRunTime);
	}

	public java.util.Date getJobRunTime() {
		return get("job_run_time");
	}

	public void setJobFinishTime(java.util.Date jobFinishTime) {
		set("job_finish_time", jobFinishTime);
	}

	public java.util.Date getJobFinishTime() {
		return get("job_finish_time");
	}

	public void setSuccFlg(java.lang.String succFlg) {
		set("succ_flg", succFlg);
	}

	public java.lang.String getSuccFlg() {
		return get("succ_flg");
	}

	public void setErrorMsg(java.lang.String errorMsg) {
		set("error_msg", errorMsg);
	}

	public java.lang.String getErrorMsg() {
		return get("error_msg");
	}

}
