package com.mj.bean.system;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDict<M extends BaseDict<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setDictCode(java.lang.String dictCode) {
		set("dict_code", dictCode);
	}

	public java.lang.String getDictCode() {
		return get("dict_code");
	}

	public void setDictName(java.lang.String dictName) {
		set("dict_name", dictName);
	}

	public java.lang.String getDictName() {
		return get("dict_name");
	}

	public void setOrderNum(java.lang.Integer orderNum) {
		set("order_num", orderNum);
	}

	public java.lang.Integer getOrderNum() {
		return get("order_num");
	}

}
