package com.mj.bean.system;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDictEnum<M extends BaseDictEnum<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setDictId(java.lang.Integer dictId) {
		set("dict_id", dictId);
	}

	public java.lang.Integer getDictId() {
		return get("dict_id");
	}

	public void setEnumValue(java.lang.String enumValue) {
		set("enum_value", enumValue);
	}

	public java.lang.String getEnumValue() {
		return get("enum_value");
	}

	public void setEnumCode(java.lang.String enumCode) {
		set("enum_code", enumCode);
	}

	public java.lang.String getEnumCode() {
		return get("enum_code");
	}

	public void setOrderNum(java.lang.Integer orderNum) {
		set("order_num", orderNum);
	}

	public java.lang.Integer getOrderNum() {
		return get("order_num");
	}

}
