package com.mj.bean.system;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setUserName(java.lang.String userName) {
		set("user_name", userName);
	}

	public java.lang.String getUserName() {
		return get("user_name");
	}

	public void setUserRealName(java.lang.String userRealName) {
		set("user_real_name", userRealName);
	}

	public java.lang.String getUserRealName() {
		return get("user_real_name");
	}

	public void setMobileArea(java.lang.Integer mobileArea) {
		set("mobile_area", mobileArea);
	}

	public java.lang.Integer getMobileArea() {
		return get("mobile_area");
	}

	public void setUserMobile(java.lang.String userMobile) {
		set("user_mobile", userMobile);
	}

	public java.lang.String getUserMobile() {
		return get("user_mobile");
	}

	public void setPwdSalt(java.lang.String pwdSalt) {
		set("pwd_salt", pwdSalt);
	}

	public java.lang.String getPwdSalt() {
		return get("pwd_salt");
	}

	public void setUserPassword(java.lang.String userPassword) {
		set("user_password", userPassword);
	}

	public java.lang.String getUserPassword() {
		return get("user_password");
	}

	public void setUserType(java.lang.Integer userType) {
		set("user_type", userType);
	}

	public java.lang.Integer getUserType() {
		return get("user_type");
	}

	public void setBizId(java.lang.String bizId) {
		set("biz_id", bizId);
	}

	public java.lang.String getBizId() {
		return get("biz_id");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setValidFlg(java.lang.String validFlg) {
		set("valid_flg", validFlg);
	}

	public java.lang.String getValidFlg() {
		return get("valid_flg");
	}

	public void setLanguage(java.lang.Integer language) {
		set("language", language);
	}

	public java.lang.Integer getLanguage() {
		return get("language");
	}

	public void setOpenId(java.lang.String openId) {
		set("open_id", openId);
	}

	public java.lang.String getOpenId() {
		return get("open_id");
	}

	public void setLastestLoginIp(java.lang.String lastestLoginIp) {
		set("lastest_login_ip", lastestLoginIp);
	}

	public java.lang.String getLastestLoginIp() {
		return get("lastest_login_ip");
	}

	public void setLastestLoginTime(java.util.Date lastestLoginTime) {
		set("lastest_login_time", lastestLoginTime);
	}

	public java.util.Date getLastestLoginTime() {
		return get("lastest_login_time");
	}

	public void setCreator(java.lang.String creator) {
		set("creator", creator);
	}

	public java.lang.String getCreator() {
		return get("creator");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setUpdator(java.lang.String updator) {
		set("updator", updator);
	}

	public java.lang.String getUpdator() {
		return get("updator");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}

	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

}
