package com.mj.bean.system;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMenu<M extends BaseMenu<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setPlatformNode(java.lang.String platformNode) {
		set("platform_node", platformNode);
	}

	public java.lang.String getPlatformNode() {
		return get("platform_node");
	}

	public void setMenuName(java.lang.String menuName) {
		set("menu_name", menuName);
	}

	public java.lang.String getMenuName() {
		return get("menu_name");
	}

	public void setMenuNameEn(java.lang.String menuNameEn) {
		set("menu_name_en", menuNameEn);
	}

	public java.lang.String getMenuNameEn() {
		return get("menu_name_en");
	}

	public void setMenuIcon(java.lang.String menuIcon) {
		set("menu_icon", menuIcon);
	}

	public java.lang.String getMenuIcon() {
		return get("menu_icon");
	}

	public void setFatherId(java.lang.String fatherId) {
		set("father_id", fatherId);
	}

	public java.lang.String getFatherId() {
		return get("father_id");
	}

	public void setMenuAction(java.lang.String menuAction) {
		set("menu_action", menuAction);
	}

	public java.lang.String getMenuAction() {
		return get("menu_action");
	}

	public void setNodeFlg(java.lang.String nodeFlg) {
		set("node_flg", nodeFlg);
	}

	public java.lang.String getNodeFlg() {
		return get("node_flg");
	}

	public void setOrderNum(java.lang.Integer orderNum) {
		set("order_num", orderNum);
	}

	public java.lang.Integer getOrderNum() {
		return get("order_num");
	}

	public void setModule(java.lang.Integer module) {
		set("module", module);
	}

	public java.lang.Integer getModule() {
		return get("module");
	}

	public void setValidFlg(java.lang.String validFlg) {
		set("valid_flg", validFlg);
	}

	public java.lang.String getValidFlg() {
		return get("valid_flg");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setCreator(java.lang.String creator) {
		set("creator", creator);
	}

	public java.lang.String getCreator() {
		return get("creator");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}

	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

	public void setUpdator(java.lang.String updator) {
		set("updator", updator);
	}

	public java.lang.String getUpdator() {
		return get("updator");
	}

}
