package com.mj.bean.system;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseExcelImportLog<M extends BaseExcelImportLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setSellerId(java.lang.String sellerId) {
		set("seller_id", sellerId);
	}

	public java.lang.String getSellerId() {
		return get("seller_id");
	}

	public void setBizType(java.lang.Integer bizType) {
		set("biz_type", bizType);
	}

	public java.lang.Integer getBizType() {
		return get("biz_type");
	}

	public void setImporter(java.lang.String importer) {
		set("importer", importer);
	}

	public java.lang.String getImporter() {
		return get("importer");
	}

	public void setImportDate(java.util.Date importDate) {
		set("import_date", importDate);
	}

	public java.util.Date getImportDate() {
		return get("import_date");
	}

	public void setImportFile(java.lang.String importFile) {
		set("import_file", importFile);
	}

	public java.lang.String getImportFile() {
		return get("import_file");
	}

	public void setImportRecords(java.lang.Integer importRecords) {
		set("import_records", importRecords);
	}

	public java.lang.Integer getImportRecords() {
		return get("import_records");
	}

	public void setAttachId(java.lang.String attachId) {
		set("attach_id", attachId);
	}

	public java.lang.String getAttachId() {
		return get("attach_id");
	}

	public void setCreator(java.lang.String creator) {
		set("creator", creator);
	}

	public java.lang.String getCreator() {
		return get("creator");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public void setUpdator(java.lang.String updator) {
		set("updator", updator);
	}

	public java.lang.String getUpdator() {
		return get("updator");
	}

	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}

	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

}
