package com.mj.bean.system;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseExceptionLog<M extends BaseExceptionLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setErrMsg(java.lang.String errMsg) {
		set("err_msg", errMsg);
	}

	public java.lang.String getErrMsg() {
		return get("err_msg");
	}

	public void setErrTime(java.util.Date errTime) {
		set("err_time", errTime);
	}

	public java.util.Date getErrTime() {
		return get("err_time");
	}

	public void setRootPath(java.lang.String rootPath) {
		set("root_path", rootPath);
	}

	public java.lang.String getRootPath() {
		return get("root_path");
	}

	public void setHandleFlg(java.lang.String handleFlg) {
		set("handle_flg", handleFlg);
	}

	public java.lang.String getHandleFlg() {
		return get("handle_flg");
	}

	public void setHandleDesc(java.lang.String handleDesc) {
		set("handle_desc", handleDesc);
	}

	public java.lang.String getHandleDesc() {
		return get("handle_desc");
	}

	public void setHandleTime(java.util.Date handleTime) {
		set("handle_time", handleTime);
	}

	public java.util.Date getHandleTime() {
		return get("handle_time");
	}

}
